### ISSUE TITLE
Ohhh snap updates! Release ETA? Fjordur compatibility?

### ISSUE THREAD

**Issue by vertyco** [miragedmuk/ASV#1]
Hey man awesome to see updates! Do you have a rough ETA for the next .exe release? And the current version doesnt seem to work with the Fjordur map that wildcard launched as an official map recently.

Also do you have a discord or anywhere where i can bug you instead of using git issues? :p

Thanks for your time and an awesome app!
Alex

**Comment by vertyco** [comment]
ALSO, do you have a Patreon or Ko-fi? I'd like to support this project

**Comment by miragedmuk** [comment]
@vertyco - I send you a friend request on discord to let you know I retired the old branch and now work on this one. CyberMirageUK.  I'll look at the official Fjordur release this evening after work.  Find that they often change things ever so slightly when going from MOD to official sponsor and I need to update the co-ordinate system.  Will let you know when I have an update.

**Comment by vertyco** [comment]
Awesome! it works thank you, could you shoot me another friend request? i may have declined it by accident not realizing it was you lol

Thanks again!
