### ISSUE TITLE
Tribes in ASV_Tribe.json export showing members that have since left the tribe

### ISSUE THREAD

**Issue by vertyco** [miragedmuk/ASV#11]
When exporting tribes, all of them show every member that has ever been in that tribe.

To give some context, we have a tribe limit of 6 on the server.
For example, one tribe in the export shows 17 people currently in the members list.
In reality, 11 of these members are not actually in the tribe anymore.

This is a little difficult to further explain as there are no errors, and it has been like this since before version 5. But I only now remembered to bring it up.

Below is another example of a tribe that (in reality) has 9 members, but still shows the old members.
This will always show the same way until the map is wiped, the old members are always shown regardless of how much time passes before running the export again.
![image](https://github.com/miragedmuk/ASV/assets/58824393/57426e24-ccee-4ce3-b203-4ec316b986de)

**Comment by miragedmuk** [comment]
Can you check it again on the latest release and let me know if this has been resolved?

**Comment by vertyco** [comment]
Will check this again with the newest release soon hopefully and let you know

**Comment by vertyco** [comment]
@miragedmuk Can confirm that this issue still exists with the most recent version.

**Comment by vertyco** [comment]
actually let me do some more testing before you go on a wild goose hunt, will post here again after

**Comment by vertyco** [comment]
Okay i've done some testing and i can replicate the issue with the newest version. Found a tribe with 7 members in it, but they only have 6, one of the members is an old one.

**Comment by miragedmuk** [comment]
.arktribe files contain a "members" list and is used in-game as the source of truth of who is in  what tribe.

.arkprofile data also contains a "TargetingTeam" property - which relates to the last tribe that player profile belonged to.  For display purposes ASV uses this data to add them into the appropriate tribe even though they technically aren't in that tribe anymore (missing from .arktribe).  

I'll re-think how this is allocated and possibly reset the TargetingTeam for any .arkprofile not in the members list of the .arktribe file data - pushing them out into their own "Tribe of CharacterName"

**Comment by miragedmuk** [comment]
Fixed in latest release.
