### ISSUE TITLE
Content Failed to Load

### ISSUE THREAD

**Issue by hi-fox** [miragedmuk/ASV#12]
Randomly getting a content failed to load issue. Program works flawlessly 90% of the time but every now and then refuses to read my save file no matter what I try, reloading, exiting the game, manually saving etc. 

https://file.io/aaEOQz0WnxGV - Ark Save file and asvlog.log

No mods installed.

**Comment by miragedmuk** [comment]
Related to non unique id's being stored with cryo creature and status data.

Latest release should fix this by always allocating new UUID values for cryo object data.
