### ISSUE TITLE
in ASV_tamed.json, id and dinoid is the same code

### ISSUE THREAD

**Issue by Sir-Dodo** [miragedmuk/ASV#14]
I have compared the ID obtained in the json file with the ID obtained through ArkServerApi and they have nothing to do with each other (DinoID1Field, DinoID2Field). It may be an error? The truth is that it would be great to be able to work with both systems and have the identifiers match.

**Comment by miragedmuk** [comment]
I just re-used whatever was used for ASE. If you know how to get the actual DinoId from the DinoID2 and DinoID2 fields please feel free to provide this information and I will update the source code as required. 

Currently this is what is used to determine the DinoId:

DinoID = maleId1 << 32 | (maleId2 & 0xFFFFFFFFL)

**Comment by miragedmuk** [comment]
Checking the codes used in-game it appears to be a string concatenation of DinoId1 and DinoId2 values then combined back into a long number.

DinoID1 = **121554212**
DinoID2 = _441845146_
IGID = **121554212**_441845146_

I'll sort it in next release.

**Comment by Sir-Dodo** [comment]
Great! Thank you! ^^
