### ISSUE TITLE
Unable to access ARK file as "used by another process"

### ISSUE THREAD

**Issue by hi-fox** [miragedmuk/ASV#15]
Hi, new issue here: When i try and load the ark file in ASV it gives me the "content failed to load" error and the log file mentions the file is used by another process. 

Ark file and log file attached

https://file.io/evjm84vxnZoW

On a side note, I did message on Reddit but unsure if you're that active - do you have a discord for this application to follow updates and/or known bugs?

**Comment by hi-fox** [comment]
As reference I am getting the same error after attempting with version 5.0.0.18 too

**Comment by miragedmuk** [comment]
Not sure what I can do to resolve this one.   I can't override operating system locks.  I have had this a couple times on my single player and had to close ASV and ARK and then try again.  Obviously one was fighting the other.

**Comment by hi-fox** [comment]
No worries, if it's not on your end I will close it
