### ISSUE TITLE
ASVexport doesn’t work with ASA

### ISSUE THREAD

**Issue by Sir-Dodo** [miragedmuk/ASV#16]
ASVexport doesn’t work with ASA

**Comment by miragedmuk** [comment]
In what way?  I have people using ASVExport with ASA and not reporting any issues other than some inventory stuff not getting exported.

**Comment by Sir-Dodo** [comment]
With 5.0.0.16 I started leaving empty jsons starting with the new version of ASA. With 5.0.0.18 it does not generate new json directly for me.

**Comment by Sir-Dodo** [comment]
Ok, I didn't say anything. It seems to have started working well. Sorry for the disturbances
