### ISSUE TITLE
content failed to load

### ISSUE THREAD

**Issue by scratch87** [miragedmuk/ASV#2]
hi, after the most recent ark server updates I am getting the content failed to load message for savegame.ark

**Comment by vertyco** [comment]
What version are you on? The most recent version is 4.4.0.0 and is working for me with the latest updates.

Link to release: https://drive.google.com/file/d/1YNOGw3MLYV4dxh37n5XfOsPfVW2nneUU/view

**Comment by scratch87** [comment]
yes I try also this, but is not working (ark v.349.13) I read on the ark forum, miragedmuk just found a solution/fix, I'm waiting for the new version. many tnx for the reply
