### ISSUE TITLE
Add `DestroyWildDinoClasses <ClassName> 1` to suggested wild creature commands

### ISSUE THREAD

**Issue by axieum** [miragedmuk/ASV#21]
Does the `DestroyAll <ClassName> 1` command also destroy tamed creatures too? If so, can we please add the wild variant command so we can run it via RCON.

**Comment by miragedmuk** [comment]
Yes it does.

If you let me know the command needed for wilds only I will get it added to the next release.

**Comment by miragedmuk** [comment]
Added for next release.  Also removed the very dangerous DestroyAll - the command you provided is quite a bit safer if accidentally clicked :)
