### ISSUE TITLE
Feature Request - Show Alpha Animals

### ISSUE THREAD

**Issue by abyss412** [miragedmuk/ASV#23]
Sorry if i write on the wrong place for this. 

I would like to ask if you can show all Alpha Dinos on the Map. Maybe with own Tab or maybe easier as a Flag at the normal Dino List in the Table.

Regards
Norbert

p.s. You did something really cool! It is very helpful to remove old stuff from old members. Can manage my cluster much more efficiently.

**Comment by miragedmuk** [comment]
You can already view alphas - just un-tick the "Tameable" option.
