### ISSUE TITLE
dont want to say its a bug, but a heads up 

### ISSUE THREAD

**Issue by stolenvw** [miragedmuk/ASV#25]
running it on the ARK: Survival Ascended Scorched Earth .ark file gives no info and empty .json files.

**Comment by miragedmuk** [comment]
Its most definitely not a bug.  Adding NEW map support is a "feature request" if anything.

**Comment by miragedmuk** [comment]
Added support for Scorched Earth Ascended - 5.1.0.0.  Source code updated and checked-in.
