### ISSUE TITLE
TheCenter_WP Compatibility

### ISSUE THREAD

**Issue by Sir-Dodo** [miragedmuk/ASV#28]
We have a new map, I have tried to work with it but it is not possible. I have tried by command with asv export.

**Comment by miragedmuk** [comment]
I'm waiting to see if there will be a new resource / explorer map for ASA before applying this change.   If no new map is made available I'll add the support using the map image from ASE if possible.

For now - to add basic support simply add this into your maps.json file:

`    {
      "MapName": "The Center (Ascended)",
      "Filename": "thecenter_wp.ark",
      "ImageFile": "map_grid.png",
      "LatShift": 32.5,
      "LatDiv": 10375,
      "LonShift": 50.5,
      "LonDiv": 10375
    }`

**Comment by Sir-Dodo** [comment]
![Sin título](https://github.com/miragedmuk/ASV/assets/158285857/24b0c678-47f1-419f-a6ef-0c47e1fcad50)
;)

**Comment by Sir-Dodo** [comment]
And add this in creaturemap:

{
      "ClassName": "FireLion_Character_BP_C",
      "FriendlyName": "Pyromane",
      "BlueprintPath": "\"Blueprint'/Game/ASA/Dinos/FireLion/FireLion_Character_BP.FireLion_Character_BP'\""
    },
    {
      "ClassName": "Shastasaurus_Character_BP_C",
      "FriendlyName": "Shastasaurus",
      "BlueprintPath": "\"Blueprint'/Game/ASA/Dinos/Shastasaurus/Shastasaurus_Character_BP.Shastasaurus_Character_BP'\""
    }

**Comment by miragedmuk** [comment]
Added, checked-in and included in release 5.1.0.5.  Thank you for the image and creature map information.
