### ISSUE TITLE
Astraeos (ark ascended) does not load data

### ISSUE THREAD

**Issue by trksh0t** [miragedmuk/ASV#32]
Seems as though save files from the new map Astraeos do not load properly

**Comment by miragedmuk** [comment]
I only have single player games to test and it appears to be working for me.  

If you would like me to investigate, please provide a download link where I can debug against one of your backups.

**Comment by miragedmuk** [comment]
Thanks for that. What are you attempting to do with this?  Arkviewer appears to load it without any issues.  

If you're not using ArkViewer then it's probably that the maps.json provided in .net6.0 doesn't contain Astraeos - copy maps.json from .net6.0-windows and it should work for ASVExport and ASVBot.

**Comment by trksh0t** [comment]
Thanks for thee quick reply - I am using ASV 5.1.0.13 and when loading the (offline) file I shared with you the status says the file is loaded but all information on all tabs appears to be empty. When I do a similar process of other maps like Island/Center then it works as expected. Perhaps I am doing something wrong?

________________________________

**Comment by miragedmuk** [comment]
I'm not sure - I haven't made any changes to the code since releasing 5.1.0.13 and using the file you provided it all appears to be working as expected.

Does the map image show when you click the world icon? Maybe you have an older version of maps.json or something.

![image](https://github.com/user-attachments/assets/f31d5761-2d69-4274-8d71-9e630c4ac71b)

**Comment by trksh0t** [comment]
I believe my maps.json is out of date. I tried to add it myself but its still not working. 
![image](https://github.com/user-attachments/assets/c9c4e769-995c-41cf-99ff-8e0003663b7c)
![image](https://github.com/user-attachments/assets/342495df-ced7-4e98-8f07-45ff1bdbbdaf)
![image](https://github.com/user-attachments/assets/4a0f971b-2dfa-47bb-98ef-b6b16ffa08a1)

**Comment by trksh0t** [comment]
That worked thank you! Where did you get this information?

 { "MapName": "Astraeos (Ascended)", "Filename": "astraeos_wp.ark", "ImageFile": "map_astraeos.png", "LatShift": 50.0, "LatDiv": 16000.0, "LonShift": 50.0, "LonDiv": 16000.0 } ] } 
 
 Perhaps in the future if I can find it myself I won't have to ask :) Specifically asking about the coordinates I guess

**Comment by miragedmuk** [comment]
I have to assess each map when it gets released or people ask for suppor to be added. 

In-game I go to a few spots making note of the CCC and GPS co-ords.  

I then plug that into a spreadsheet and play with the lat/lon div values until the calculted lat/lon approximately match the in-game gps lat/lon

**Comment by miragedmuk** [comment]
One of the other guys working on a Java parser is smarter than me and my guess-work and gets more accuracy using ChatGPT to work it out :)
