### ISSUE TITLE
Spawn Exact Dino Option

### ISSUE THREAD

**Issue by Worldgate** [miragedmuk/ASV#33]
There used to be a method for extracting the spawn command to extract an exact copy of the wild dino from inside ASV but it's missing, now it just does.

cheat GMSummon "Cherufe_Character_BP_C" 300

**Comment by miragedmuk** [comment]
Will be re-added in next release.  

Its all defined in commands.json so you could re-add it yourself but there is currently a bug where it doesn't output empty defaults for the wild tab.

**Comment by miragedmuk** [comment]
Included with latest release.
