### ISSUE TITLE
Ark Ascended Support

### ISSUE THREAD

**Issue by estudianteisis** [miragedmuk/ASV#6]
Hey, do you support/are you planning on supporting the new remake of Ark? Is that a challenging thing to do?

**Comment by miragedmuk** [comment]
As soon as we can determine the file format I will look into providing support.  Unfortunately it appears to be completely different to that of ASE and is based on a SqlLite database with game data I don't recognise.  

I don't have any in depth knowledge of the file formats and have only made small changes to the toolkit used by ASV based on discovery over time.  If others are able to decipher the format I can then dig deeper and see what there is to use within ASV.
