### ISSUE TITLE
Issue with the exporter

### ISSUE THREAD

**Issue by DerNap** [miragedmuk/ASV#7]
I am trying to get an export of the data in the *.arkprofile files. I did that in the past with arktools unless it stopped working. Now I came across your ASVExport.exe and tried to use this instead.

I thought I could export *.arkprofile files individually, but when trying to use the exporter along with an *.arkprofile file directly, I get the following output/error:
ASV Command Line Started with 4 parameters.
CommandLineArg-0 = C:\Tools\Ark\ASV\4.5.2.0\ASVExport.dll
CommandLineArg-1 = arkprofile
CommandLineArg-2 = c:\tmp\XXXXXXXXXXXXX.arkprofile
CommandLineArg-3 = c:\tmp\output\
Failed export for: c:\tmp\XXXXXXXXXXXXX.arkprofile - Ex: Found unknown Version 1

Digging in the code it seemed to me the exporter was expecting an ark-archive as parameter so I guessed it would export all the profiles in one go instead of exporting an individual *.arkprofile. 
When I use the exporter with the map-savefile, there is no error, but also no output.
ASV Command Line Started with 4 parameters.
CommandLineArg-0 = C:\Tools\Ark\ASV\4.5.2.0\ASVExport.dll
CommandLineArg-1 = arkprofile
CommandLineArg-2 = c:\tmp\TheIsland.ark
CommandLineArg-3 = c:\tmp\output
Read ended in 00:00:15.5476234
Stored containers identified in 00:00:00.2147126
Properties loaded in 00:00:01.4185354
Objects added in 00:00:00.0043137
Completed export for: c:\tmp\TheIsland.ark

The c:\tmp\output dir is empty after this command though.

Do I still miss the point in the "arkprofile" command option of the exporter or is this feature kinda broken since unused by ASV?

**Comment by miragedmuk** [comment]
The point was simply to allow export of the last x months of .arkprofile and .arktribe data for saves that have since migrated to using --UseStore which puts that data into the .ark file instead of external .arkprofile/.arktribe files as it was previously.

Honestly can't see anybody using this option and it was only integrated as somebody requested it to try and make migration from the last official backups to unofficial easier (not sure it did)

Currently deep in code and data trying to add support for Ark Survival Ascended but I will check out the .arkprofile export and this "issue" when I get time.

**Comment by miragedmuk** [comment]
This is the correct way of using it:

When I use the exporter with the map-savefile, there is no error, but also no output.
ASV Command Line Started with 4 parameters.
CommandLineArg-0 = C:\Tools\Ark\ASV\4.5.2.0\ASVExport.dll
CommandLineArg-1 = arkprofile
CommandLineArg-2 = c:\tmp\TheIsland.ark
CommandLineArg-3 = c:\tmp\output
Read ended in 00:00:15.5476234
Stored containers identified in 00:00:00.2147126
Properties loaded in 00:00:01.4185354
Objects added in 00:00:00.0043137
Completed export for: c:\tmp\TheIsland.ark

However I'm guessing the .ark file you are passing in has not been saved with profiles/tribe data inside it.. so nothing to export back out into .arktribe and .arkprofile files.

No issues found.
