### ISSUE TITLE
Compile ASVExport only for Windows and Linux

### ISSUE THREAD

**Issue by LotekHeavy** [miragedmuk/ASV#8]
Before I describe the problem, I want to briefly thank you for your precious time. The ASV is unique and is the best admin tool for my small ARK cluster :-) I must preface this by saying I am not at all familiar with .NET or Visual Studio. However, my goal would be to get ASVExport.exe running on Linux (Ubuntu). This should generally be possible (atleast I could get running the ASVEXport under Linux)

However, I have a problem that whenever I clone your repository and build and publish it (only the ASVExport Project) via Visual Studio, I can run the ASVExport.exe (or ASVExport on Linux), but when exporting, the desired JSON file is practically empty, containing only: []. When I use your binary files directly, it works and generates a ~6MB File of all wild dinos.

Example:
D:\Users\Marcel\Dokumente\Development\ASV>ASVExport.exe wild "h:\ark\maps\island\ShooterGame\Saved\SavedArks\TheIsland.ark" "D:\Users\Marcel\Desktop\export\file.json"

```
ASV Command Line Started with 4 parameters.
CommandLineArg-0 = D:\Users\Marcel\Dokumente\Development\ASV\ASVExport.exe
CommandLineArg-1 = wild
CommandLineArg-2 = h:\ark\maps\island\ShooterGame\Saved\SavedArks\TheIsland.ark
CommandLineArg-3 = D:\Users\Marcel\Desktop\export\file.json
Stored containers identified in 00:00:00.0108461
Properties loaded in 00:00:00.0932692
Objects added in 00:00:00.0007793
Read ended in 00:00:01.1691361
Exporting JSON (wild) for: h:\ark\maps\island\ShooterGame\Saved\SavedArks\TheIsland.ark
Completed export for: h:\ark\maps\island\ShooterGame\Saved\SavedArks\TheIsland.ark
```

Attached is also a logfile from the build (or rebuild) and from the publish:
[logfile_build.txt](https://github.com/miragedmuk/ASV/files/13493587/logfile_build.txt)
[logfile_publish.txt](https://github.com/miragedmuk/ASV/files/13493588/logfile_publish.txt)

What I do wrong?
Maybe you have a small tip on which direction I should look...
thx!

**Comment by miragedmuk** [comment]
Unfortunately I have never used any form of Linux so have no idea what might be going wrong. I know the windows compiled binaries do what they should as many out there are using it.

**Comment by LotekHeavy** [comment]
just a note its working now (maybe I was just to dump earlier)

with the latest version [5.1.0.12](https://github.com/miragedmuk/ASV/releases/tag/5.1.0.12) I could make it working under linux without any problems (or compiling). steps for me was under ubuntu 24.04:

sudo add-apt-repository ppa:dotnet/backports
sudo apt-get install -y dotnet-runtime-6.0

Download your ZIP File and only use the ".net6.0" and command is like:
dotnet ASVExport.dll <command> <arkmap> <exportfile>

Example for all tamed creatures:
dotnet /home/ark/share/ASV/ASVExport.dll tamed /home/ark/var/asv-map/TheIsland.ark /home/ark/var/asv-json/theisland_tamed.json

thx
