### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by Worldgate** [miragedmuk/ASV#9]
Just thought I would mention that the UI doesn't scale well.  1080p, 2k, 4k, still same effect.  
![image](https://github.com/miragedmuk/ASV/assets/7388655/8b09b26e-b1ed-4ca0-bd56-669e80ef110d)

**Comment by miragedmuk** [comment]
How do you change this?  Scaling isn't something I've ever had to work with as all my apps usually target specific tills and resolutions.

I checked the FTP browser form for resizing and it seems to work ok and keep alignment as expected with that.

Be interesting to see what is available for "scaling" in Winforms.

**Comment by Worldgate** [comment]
I didn't change anything, I am on windows 11, 4k resolution.  It gets all weird at 4k.

**Comment by miragedmuk** [comment]
I don't have any monitor capable of more than 1080 but just done a quick Google and sounds like adding a setting to my program startup should help.

Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);

Just working on a few other bits and I'll get it update for you to try it out and let me know.

**Comment by miragedmuk** [comment]
Just did some basic testing at 1080 - scaling of 100%, 125% and 150%.

Had to swap app between monitors to pick up the changes properly but it looked aligned at least at all scales in latest release.

https://github.com/miragedmuk/ASV/releases/tag/ASA

Please let me know if this resolves the issue for you.

Thanks

**Comment by miragedmuk** [comment]
Assuming that this is now resolved. No response received but seemed to work ok when scaled to 125/150% on my system at 1080 resolution.
